version: '3.8'

services:
  api:
    build:
      context: ..  # Apunta al directorio raíz NewLens/
      dockerfile: docker/flask-api.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../api/fakenews/modelos:/app/fakenews/modelos  # Mapea la carpeta de modelos
    restart: always

  frontend:
    build:
      context: ..  # Apunta al directorio raíz NewLens/
      dockerfile: docker/php-frontend.Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - api
    restart: always